### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by rmoriz** [prauscher/vl#37]
Hallo,

wie schauts mit Tests aus?

Grüße

**Comment by Waldteufel** [comment]
Wären definitiv eine gute Idee… ;-)
Im Moment ist erstmal angedacht, das DB-Backend auf  https://github.com/maritz/nohm umzustellen, aber wenn das durch ist, sollten wir mal ein paar systematische Unit-Tests einbauen. Die AJAX-Aufrufe sowie die Socket.IO Events lassen sich ja halbwegs testen.
