### ISSUE TITLE
automatische Vergabe von Antragsnummern (abhängig von Kategorie+Subkategorie)

### ISSUE THREAD

**Issue by prauscher** [prauscher/vl#43]
irgendwas mit nem Counter und sprintf? Kann ruhig ne hohe Komplexität haben, soo häufig kommt das ja auch nicht vor.

**Comment by Waldteufel** [comment]
Vorsicht, falls #48 mit Duplizieren implementiert wird!

**Comment by prauscher** [comment]
Da javascript kein sprintf kann irgendwas anderes ;_;
