### ISSUE TITLE
Antrag-Templates für häufige Anträge 

### ISSUE THREAD

**Issue by prauscher** [prauscher/vl#48]

**Comment by Waldteufel** [comment]
Kategorie „Templates“ + Duplizieren-Funktion?
(Folien duplizieren geht ja schon)

**Comment by prauscher** [comment]
Idee: In der Config einen Hash für Templates, in der die Vorlage abgelegt ist. Daraus dann eine Dropdown-Liste generieren wie bei "Neuer Antrag".

Beispiel:
"motiontemplates": {"Blah": {classid:"sfsdf", "argumentation": "Weil ich es kann"}, "Other Template":{...}}
