### ISSUE TITLE
timer Hintergrundfarbe von backend-Farbe trennen

### ISSUE THREAD

**Issue by levu42** [prauscher/vl#5]
Im Backend braucht man Signalfarben, die man gut unterscheiden kann (leuchtende Farben z.B., die alle deutlich unterschiedlich aussehen). Im Frontend hingegen nimmt man vermutlich dezente, helle Farben als Hintergrundfarben. Im Moment ist das jedoch die gleiche Farbe

**Comment by prauscher** [comment]
Die Timer-Farben werden im Backend ja faktisch nicht benutzt, also kann man da auch direkt die dezente Farbe einstellen. Mehrere Farben verwirren da imho mehr.
