### ISSUE TITLE
Bug: Drag and Drop

### ISSUE THREAD

**Issue by ghost** [prauscher/vl#65]
In der Version vom BPT 2012.2 treten einige Fehler beim Verschieben von Anträgen und Tagesordnungspunkten auf.

Folgende Probleme habe ich beobachtet:

Der Eintrag wird beim Verschieben oft einen Eintrag weiter oben platziert als dort wo er eigentlich abgelegt wurde.

Manchmal erscheinen Einträge nach dem Verschieben doppelt. Nach einem Reload der Seite wird dann wieder nur einen Eintrag angezeigt.

Die Sortierung auf den Agendafolien ist total durcheinander.

**Comment by prauscher** [comment]
Ursache fürs erste: in treeTable wird das Position-Flag nie geupdated. ToDo: Serverseitig Updates der Positions bekanntgeben.

**Comment by prauscher** [comment]
Nötige Änderungen an treeTable (beim einfügen): Sofern die Position schon verwendet wird, alle Nachgänger um eines erhöhen.
